name = "veternitzz/progressbar"
version = "1.0.1"
description = "The progress bar from pesde/toolchainlib ported to a pesde package."
authors = ["Anthony LaPeter <anthonylapeter@gmail.com>", "Erica Marigold <hi@devcomp.xyz>"]
repository = "https://github.com/veternitzz/progressbar"
license = "MIT"
includes = ["lib.luau", "pesde.toml", "LICENSE", "README.md", "LICENSE-MIT"]

[target]
environment = "lune"
lib = "lib.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
