name = "lukadev_0/option"
version = "1.2.0"
description = "Option<T> type in Luau"
license = "MIT"
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)"]
repository = "https://github.com/lukadev-0/util.luau"
private = false
includes = ["LICENSE", "README.md", "lib", "pesde.toml"]

[target]
environment = "lune"
lib = "lib/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
